package form;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManajemenPelanggan extends javax.swing.JFrame {

    private final Connection conn;
    private Statement stat;
    private PreparedStatement pst;
    private ResultSet res;
    private final DefaultTableModel model;
    private DateTimeFormatter dtf;
    private LocalDate now;

    public ManajemenPelanggan() {
        
        initComponents();
        conn = koneksi.Koneksi.GetConnection();
        model = new DefaultTableModel();
        model.addColumn("No Meter");
        model.addColumn("Daya");
        model.addColumn("Jumlah KWH");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Total Tagihan");
        model.addColumn("Tanggal Join");
        model.addColumn("No Telp");
        tbl_pelanggan.setModel(model);
        dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        now = LocalDate.now();
        txt_tanggal.setText(String.valueOf(now));

        // menampilkan data pelanggan
        getDataPelanggan();
        // data tarif/daya
        getDataTarif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_noMeter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kwh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pelanggan = new javax.swing.JTable();
        btn_baru = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        txt_keyword = new javax.swing.JTextField();
        cb_daya = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbl_total_tagihan = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        txt_tanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_notelp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("DATA PELANGGAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 340, 42);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("No Meter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 120, 70, 14);
        getContentPane().add(txt_noMeter);
        txt_noMeter.setBounds(223, 117, 401, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tarif/Daya");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 158, 70, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jumlah KWH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(72, 198, 80, 14);

        txt_kwh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kwhKeyReleased(evt);
            }
        });
        getContentPane().add(txt_kwh);
        txt_kwh.setBounds(223, 195, 64, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 236, 50, 14);
        getContentPane().add(txt_nama);
        txt_nama.setBounds(223, 233, 401, 20);
        getContentPane().add(txt_alamat);
        txt_alamat.setBounds(223, 264, 401, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(72, 267, 60, 14);

        tbl_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pelanggan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 441, 695, 191);

        btn_baru.setText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_baru);
        btn_baru.setBounds(223, 383, 55, 23);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah);
        btn_tambah.setBounds(379, 383, 71, 23);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(456, 383, 81, 23);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(543, 383, 81, 23);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari);
        btn_cari.setBounds(624, 412, 81, 23);
        getContentPane().add(txt_keyword);
        txt_keyword.setBounds(378, 413, 228, 20);

        cb_daya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dayaActionPerformed(evt);
            }
        });
        getContentPane().add(cb_daya);
        cb_daya.setBounds(223, 155, 167, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total Tagihan: Rp.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(336, 198, 110, 14);

        lbl_total_tagihan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_total_tagihan.setText("-");
        getContentPane().add(lbl_total_tagihan);
        lbl_total_tagihan.setBounds(617, 193, 7, 20);

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(70, 70, 69, 23);
        getContentPane().add(txt_tanggal);
        txt_tanggal.setBounds(223, 295, 401, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tanggal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(72, 298, 60, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("No Telp");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(74, 333, 60, 14);
        getContentPane().add(txt_notelp);
        txt_notelp.setBounds(223, 333, 401, 20);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 60);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 720, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        // kosongkan semua field
        txt_noMeter.setText("");
        cb_daya.setSelectedItem(0);
        txt_kwh.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_keyword.setText("");
        lbl_total_tagihan.setText("");
        txt_tanggal.setText(String.valueOf(now));
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_noMeter.getText();
        int daya = Integer.parseInt(cb_daya.getSelectedItem().toString());
        int jumlahKWH = Integer.parseInt(txt_kwh.getText());
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        int total = Integer.parseInt(lbl_total_tagihan.getText());
        
        String tanggal = String.valueOf(now);

        try {
            String sql = "insert into pelanggan (no_meter, daya, jumlah_kwh, nama, alamat, total_tagihan, tanggal_join, no_telp) "
                    + "values(?,?,?,?,?,?,?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, noMeter);
            pst.setInt(2, daya);
            pst.setInt(3, jumlahKWH);
            pst.setString(4, nama);
            pst.setString(5, alamat);
            pst.setInt(6, total);
            pst.setString(7, tanggal);
            pst.setInt(8, Integer.parseInt(txt_notelp.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah Data pelanggan berhasil");
            getDataPelanggan();
            btn_baruActionPerformed(evt);
            txt_noMeter.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tambah Data pelanggan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_noMeter.getText();
        int daya = Integer.parseInt(cb_daya.getSelectedItem().toString());
        int jumlahKWH = Integer.parseInt(txt_kwh.getText());
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        String tanggal = txt_tanggal.getText();

        try {
            String sql = "update pelanggan set daya=?, jumlah_kwh=?, nama=?, alamat=?, tanggal_join=?, total_tagihan=?, no_telp=? where no_meter=?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, daya);
            pst.setInt(2, jumlahKWH);
            pst.setString(3, nama);
            pst.setString(4, alamat);
            pst.setString(5, tanggal);
            pst.setString(6, lbl_total_tagihan.getText());
            pst.setInt(7, Integer.parseInt(txt_notelp.getText()));
            pst.setString(8, noMeter);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Edit Data pelanggan berhasil");
            getDataPelanggan();
            btn_baruActionPerformed(evt);
            txt_noMeter.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Edit Data pelanggan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pelangganMouseClicked
        // TODO add your handling code here:
        int i = tbl_pelanggan.getSelectedRow();
        txt_noMeter.setText(model.getValueAt(i, 0).toString());
        cb_daya.setSelectedItem(model.getValueAt(i, 1).toString());
        txt_kwh.setText(model.getValueAt(i, 2).toString());
        txt_nama.setText(model.getValueAt(i, 3).toString());
        txt_alamat.setText(model.getValueAt(i, 4).toString());
        lbl_total_tagihan.setText((String) model.getValueAt(i, 5));
        txt_tanggal.setText(model.getValueAt(i, 6).toString());
        txt_noMeter.setEditable(false);
        txt_notelp.setText((String) model.getValueAt(i, 7));

    }//GEN-LAST:event_tbl_pelangganMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_noMeter.getText();
        try {
            String sql = "delete from pelanggan where no_meter=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, noMeter);
            pst.execute();
            JOptionPane.showMessageDialog(this, "hapus data pelanggan berhasil");
            getDataPelanggan();
            btn_baruActionPerformed(evt);
            txt_noMeter.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "hapus data pelanggan gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_keyword.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from pelanggan where no_meter LIKE '%" + noMeter + "%'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[7];
                o[0] = res.getString("no_meter");
                o[1] = res.getString("daya");
                o[2] = res.getString("jumlah_kwh");
                o[3] = res.getString("nama");
                o[4] = res.getString("alamat");
                o[5] = res.getString("total_tagihan");
                o[6] = res.getString("tanggal_join");
                model.addRow(o);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_kwhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kwhKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "select * from tarif where daya='" + cb_daya.getSelectedItem().toString() + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                int tarif = Integer.parseInt(res.getString("tarif_per_kwh"));
                int jumlah = Integer.parseInt(txt_kwh.getText());
                int total = tarif * jumlah;
                lbl_total_tagihan.setText(String.valueOf(total));
            }
        } catch (NumberFormatException | SQLException e) {
        }
    }//GEN-LAST:event_txt_kwhKeyReleased

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void cb_dayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dayaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_daya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total_tagihan;
    private javax.swing.JTable tbl_pelanggan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_keyword;
    private javax.swing.JTextField txt_kwh;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_noMeter;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables

    private void getDataPelanggan() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from pelanggan";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[8];
                o[0] = res.getString("no_meter");
                o[1] = res.getString("daya");
                o[2] = res.getString("jumlah_kwh");
                o[3] = res.getString("nama");
                o[4] = res.getString("alamat");
                o[5] = res.getString("total_tagihan");
                o[6] = res.getString("tanggal_join");
                o[7] = res.getString("no_telp");
                model.addRow(o);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void getDataTarif() {
        try {
            String sql = "select * from tarif";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                cb_daya.addItem(res.getString("daya"));
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }
}