package form;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Tarif extends javax.swing.JFrame {

    private final Connection conn;
    private Statement stat;
    private PreparedStatement pst;
    private ResultSet res;
    private final DefaultTableModel model;

    public Tarif() {
        initComponents();
        conn = koneksi.Koneksi.GetConnection();
        model = new DefaultTableModel();
        model.addColumn("Kode Tarif");
        model.addColumn("Daya");
        model.addColumn("Tarif Per KWH");
        tbl_tarif.setModel(model);

        getDataTarif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_daya = new javax.swing.JTextField();
        btn_baru = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        txt_tarif = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        txt_keyword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tarif = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("TARIF DASAR LISTRIK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(133, 11, 402, 42);
        getContentPane().add(txt_daya);
        txt_daya.setBounds(178, 139, 401, 20);

        btn_baru.setText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_baru);
        btn_baru.setBounds(215, 244, 55, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tarif per KWH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(72, 180, 80, 14);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah);
        btn_tambah.setBounds(322, 244, 71, 23);
        getContentPane().add(txt_tarif);
        txt_tarif.setBounds(178, 177, 401, 20);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(403, 244, 81, 23);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(494, 244, 81, 23);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari);
        btn_cari.setBounds(494, 289, 81, 23);
        getContentPane().add(txt_keyword);
        txt_keyword.setBounds(248, 290, 228, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Kode Tarif");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 104, 60, 14);
        getContentPane().add(txt_kode);
        txt_kode.setBounds(178, 101, 401, 20);

        tbl_tarif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tarifMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tarif);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 650, 191);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Daya");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(72, 142, 40, 14);

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(57, 74, 69, 23);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 60);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 670, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        // kosongkan semua field
        txt_kode.setText("");
        txt_daya.setText("");
        txt_tarif.setText("");
        txt_keyword.setText("");
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String kode = txt_kode.getText();
        int daya = Integer.parseInt(txt_daya.getText());
        int tarif = Integer.parseInt(txt_tarif.getText());

        try {
            String sql = "insert into tarif (kode_tarif, daya, tarif_per_kwh) "
                    + "values(?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, kode);
            pst.setInt(2, daya);
            pst.setInt(3, tarif);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah Data tarif berhasil");
            getDataTarif();
            btn_baruActionPerformed(evt);
            txt_kode.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tambah Data tarif Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String kode = txt_kode.getText();
        int daya = Integer.parseInt(txt_daya.getText());
        int tarif = Integer.parseInt(txt_tarif.getText());

        try {
            String sql = "update tarif  set daya=?, tarif_per_kwh=? where kode_tarif=?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, daya);
            pst.setInt(2, tarif);
            pst.setString(3, kode);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah Data tarif berhasil");
            getDataTarif();
            btn_baruActionPerformed(evt);
            txt_kode.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tambah Data tarif Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String kode = txt_kode.getText();
        try {
            String sql = "delete from tarif where kode_tarif=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, kode);
            pst.execute();
            JOptionPane.showMessageDialog(this, "hapus data tarif berhasil");
            getDataTarif();
            txt_kode.setEditable(true);
            btn_baruActionPerformed(evt);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "hapus data tarif gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_keyword.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from tarif where no_meter LIKE '%" + noMeter + "%'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[6];
                o[0] = res.getString("no_meter");
                o[1] = res.getString("daya");
                o[2] = res.getString("jumlah_kwh");
                o[3] = res.getString("nama");
                o[4] = res.getString("alamat");
                o[5] = res.getString("golongan");
                model.addRow(o);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tbl_tarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tarifMouseClicked
        // TODO add your handling code here:
        int i = tbl_tarif.getSelectedRow();
        txt_kode.setText(model.getValueAt(i, 0).toString());
        txt_daya.setText(model.getValueAt(i, 1).toString());
        txt_tarif.setText(model.getValueAt(i, 2).toString());
        txt_kode.setEditable(false);

    }//GEN-LAST:event_tbl_tarifMouseClicked

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tarif;
    private javax.swing.JTextField txt_daya;
    private javax.swing.JTextField txt_keyword;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_tarif;
    // End of variables declaration//GEN-END:variables

    private void getDataTarif() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from tarif";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[3];
                o[0] = res.getString("kode_tarif");
                o[1] = res.getString("daya");
                o[2] = res.getString("tarif_per_kwh");
                model.addRow(o);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
}