package form;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class transaksi extends javax.swing.JFrame {

    private final Connection conn;
    private ResultSet res;
    private Statement stat;
    private PreparedStatement pst;
    private final DefaultTableModel model;
    private LocalDate now;
    private int id_transaksi;

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        now = LocalDate.now();
        conn = koneksi.Koneksi.GetConnection();
        model = new DefaultTableModel();
        model.addColumn("#ID");
        model.addColumn("NO METER");
        model.addColumn("TGL TAGIHAN");
        model.addColumn("TGL BAYAR");
        model.addColumn("TOTAL BAYAR");
        tbl_transaksi.setModel(model);

        getDataTransaksi();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_total_tagihan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tanggalTagihan = new javax.swing.JTextField();
        txt_kwh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        cb_daya = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_noMeter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_baru = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        txt_keyword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        txt_tanggalBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_totalBayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_no_telp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("TRANSAKSI ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 10, 230, 42);

        lbl_total_tagihan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_total_tagihan.setText("-");
        getContentPane().add(lbl_total_tagihan);
        lbl_total_tagihan.setBounds(637, 182, 30, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jumlah KWH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(93, 185, 80, 14);
        getContentPane().add(txt_tanggalTagihan);
        txt_tanggalTagihan.setBounds(247, 312, 401, 20);

        txt_kwh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kwhKeyReleased(evt);
            }
        });
        getContentPane().add(txt_kwh);
        txt_kwh.setBounds(247, 182, 64, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tanggal Tagihan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(93, 315, 100, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(99, 225, 40, 14);
        getContentPane().add(txt_nama);
        txt_nama.setBounds(247, 222, 401, 20);
        getContentPane().add(txt_alamat);
        txt_alamat.setBounds(247, 272, 401, 20);

        cb_daya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dayaActionPerformed(evt);
            }
        });
        getContentPane().add(cb_daya);
        cb_daya.setBounds(247, 142, 167, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(93, 275, 50, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total Tagihan: Rp.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(357, 182, 110, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("No Meter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(93, 95, 60, 14);

        txt_noMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noMeterActionPerformed(evt);
            }
        });
        getContentPane().add(txt_noMeter);
        txt_noMeter.setBounds(247, 92, 401, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tarif/Daya");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(93, 145, 70, 14);

        btn_baru.setText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_baru);
        btn_baru.setBounds(247, 472, 55, 23);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah);
        btn_tambah.setBounds(377, 472, 71, 23);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(477, 472, 81, 23);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(567, 472, 81, 23);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari);
        btn_cari.setBounds(567, 512, 81, 23);
        getContentPane().add(txt_keyword);
        txt_keyword.setBounds(247, 512, 310, 20);

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_transaksi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 546, 860, 90);
        getContentPane().add(txt_tanggalBayar);
        txt_tanggalBayar.setBounds(247, 352, 401, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tanggal Bayar");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(93, 355, 90, 14);
        getContentPane().add(txt_totalBayar);
        txt_totalBayar.setBounds(247, 392, 401, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total Bayar");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(93, 395, 70, 14);

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak);
        btn_cetak.setBounds(688, 451, 81, 23);

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(10, 70, 69, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("No Telepon");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(93, 435, 70, 14);
        getContentPane().add(txt_no_telp);
        txt_no_telp.setBounds(247, 432, 401, 20);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 60);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 900, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kwhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kwhKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "select * from tarif where daya='" + cb_daya.getSelectedItem().toString() + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                int tarif = Integer.parseInt(res.getString("tarif_per_kwh"));
                int jumlah = Integer.parseInt(txt_kwh.getText());
                int total = tarif * jumlah;
                lbl_total_tagihan.setText(String.valueOf(total));
            }
        } catch (NumberFormatException | SQLException e) {
        }
    }//GEN-LAST:event_txt_kwhKeyReleased

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        // kosongkan semua field
        txt_noMeter.setText("");
        cb_daya.setSelectedItem(0);
        txt_kwh.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_keyword.setText("");
        lbl_total_tagihan.setText("");
        txt_tanggalTagihan.setText(String.valueOf(now));
        txt_totalBayar.setText("");
        txt_no_telp.setText("");
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_noMeter.getText();
        int daya = Integer.parseInt(cb_daya.getSelectedItem().toString());
        int jumlahKWH = Integer.parseInt(txt_kwh.getText());
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        int total = Integer.parseInt(lbl_total_tagihan.getText());

        String tanggal = String.valueOf(now);

        try {
            String sql = "insert into pelanggan (no_meter, daya, jumlah_kwh, nama, alamat, total_tagihan, tanggal_join) "
                    + "values(?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, noMeter);
            pst.setInt(2, daya);
            pst.setInt(3, jumlahKWH);
            pst.setString(4, nama);
            pst.setString(5, alamat);
            pst.setInt(6, total);
            pst.setString(7, tanggal);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah Data pelanggan berhasil");
            getDataTransaksi();
            btn_baruActionPerformed(evt);
            txt_noMeter.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tambah Data pelanggan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_noMeter.getText();
        int daya = Integer.parseInt(cb_daya.getSelectedItem().toString());
        int jumlahKWH = Integer.parseInt(txt_kwh.getText());
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        String tanggal = txt_tanggalTagihan.getText();

        try {
            String sql = "update pelanggan set daya=?, jumlah_kwh=?, nama=?, alamat=?, tanggal_join=?, total_tagihan=? where no_meter=?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, daya);
            pst.setInt(2, jumlahKWH);
            pst.setString(3, nama);
            pst.setString(4, alamat);
            pst.setString(5, tanggal);
            pst.setString(6, lbl_total_tagihan.getText());
            pst.setString(7, noMeter);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Edit Data pelanggan berhasil");
            getDataTransaksi();
            btn_baruActionPerformed(evt);
            txt_noMeter.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Edit Data pelanggan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_noMeter.getText();
        try {
            String sql = "delete from pelanggan where no_meter=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, noMeter);
            pst.execute();
            JOptionPane.showMessageDialog(this, "hapus data pelanggan berhasil");
            getDataTransaksi();
            btn_baruActionPerformed(evt);
            txt_noMeter.setEditable(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "hapus data pelanggan gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String noMeter = txt_keyword.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from pelanggan where no_meter LIKE '%" + noMeter + "%'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[7];
                o[0] = res.getString("no_meter");
                o[1] = res.getString("daya");
                o[2] = res.getString("jumlah_kwh");
                o[3] = res.getString("nama");
                o[4] = res.getString("alamat");
                o[5] = res.getString("total_tagihan");
                o[6] = res.getString("tanggal_join");
                model.addRow(o);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tbl_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_transaksiMouseClicked
        // TODO add your handling code here:
        int i = tbl_transaksi.getSelectedRow();
        String no_meter = model.getValueAt(i, 1).toString();
        System.out.println(no_meter);
        String sql = "select * from pelanggan where no_meter='" + no_meter + "'";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txt_noMeter.setText(no_meter);
                cb_daya.addItem(res.getString("daya"));
                txt_kwh.setText(res.getString("jumlah_kwh"));
                txt_nama.setText(res.getString("nama"));
                txt_alamat.setText(res.getString("alamat"));
                txt_tanggalTagihan.setText(String.valueOf(now));
                txt_tanggalBayar.setText(String.valueOf(now));
                txt_totalBayar.setText(res.getString("total_tagihan"));
                txt_no_telp.setText(res.getString("no_telp"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_transaksiMouseClicked

    private void txt_noMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noMeterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noMeterActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
       try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("..\\report\\laporanTransaksi.jasper"), null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void cb_dayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dayaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_daya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total_tagihan;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_keyword;
    private javax.swing.JTextField txt_kwh;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_noMeter;
    private javax.swing.JTextField txt_no_telp;
    private javax.swing.JTextField txt_tanggalBayar;
    private javax.swing.JTextField txt_tanggalTagihan;
    private javax.swing.JTextField txt_totalBayar;
    // End of variables declaration//GEN-END:variables

    private void getDataTransaksi() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String sql = "SELECT * FROM `transaksi`";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[5];
                o[0] = res.getString("id_transaksi");
                o[1] = res.getString("no_meter");
                o[2] = res.getString("tanggal_tagihan");
                o[3] = res.getString("tanggal_bayar");
                o[4] = res.getString("total_bayar");
                model.addRow(o);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
}